### ISSUE TITLE
Running on Ubuntu 64bit 16.04

### ISSUE THREAD

**Issue by ClintfromCanada** [ydkhatri/mac_apt#1]
Hello!  I see you tested it on 32bit Ubuntu.  On my version, everything installed correctly, but upon running it I get:

root@ubuntu:/usr/local/bin/mac_apt-0.2.6-alpha# python mac_apt.py 
Traceback (most recent call last):
  File "mac_apt.py", line 29, in <module>
    import plugins.helpers.macinfo as macinfo
  File "/usr/local/bin/mac_apt-0.2.6-alpha/plugins/helpers/macinfo.py", line 24, in <module>
    from hfs_alt import HFSVolume
  File "/usr/local/bin/mac_apt-0.2.6-alpha/plugins/helpers/hfs_alt.py", line 30, in <module>
    from btree import AttributesTree, CatalogTree, ExtentsOverflowTree
  File "/usr/local/bin/mac_apt-0.2.6-alpha/plugins/helpers/btree.py", line 19, in <module>
    from structs import *
  File "/usr/local/bin/mac_apt-0.2.6-alpha/plugins/helpers/structs.py", line 85, in <module>
    "startBlock" / Int32ub,
NameError: name 'Int32ub' is not defined

This is the excerpt from the source code of structs.py:
```
Line 84:     HFSPlusExtentDescriptor = "HFSPlusExtentDescriptor" / Struct(
Line 85:         "startBlock" / Int32ub,
Line 86:         "blockCount" / Int32ub
Line 87:     )
```
Would you happen to have any ideas on how I would tackle this problem?  I have searched for anything I can regarding Int32ub but I have been unsuccessful.  I'm assuming maybe it has something to do with 32bit but I can't be sure.

Thanks,
Clint Baker

**Comment by ydkhatri** [comment]
This has to do with the 'construct' library. Perhaps it did not install correctly. Try again with:

> sudo pip install construct

**Comment by ydkhatri** [comment]
Closing issue for lack of response. 
We've tested now with **Ubuntu 64 bit 16.04** and found no issues if you follow the installation instructions from the wiki.
