### ISSUE TITLE
Please add requirements.txt

### ISSUE THREAD

**Issue by joachimmetz** [ydkhatri/mac_apt#10]
While running mac_apt.py from git clone
`ImportError: No module named kaitaistruct`

Please add a requirements.txt file that contains information about dependencies.

only reference I found regarding "dependencies" was https://github.com/ydkhatri/mac_apt/blob/27302315b6d6f3f8b43c35823664e36509270049/plugins/helpers/spotlight_parser.py#L22

**Comment by ydkhatri** [comment]
There is a link to the wiki on the Readme.md (frontpage) which contains a page on [Installation ](https://github.com/ydkhatri/mac_apt/wiki/Installation) instructions and requirements. 

The file you've reference (with the incomplete dependencies) is from the standalone spotlight_parser, a separate [project ](https://github.com/ydkhatri/spotlight_parser) but used here.

**Comment by ydkhatri** [comment]
It's on the list of things to do.. 
:)

**Comment by joachimmetz** [comment]
https://github.com/ydkhatri/mac_apt/pull/11

**Comment by joachimmetz** [comment]
Had to disable 2 packages for now pylzfse fails to install via pip https://github.com/dimkr/pylzfse/issues/4

and pyewf in PyPI is the experimental version

**Comment by ydkhatri** [comment]
Closing this. There is no requirements file as not all dependencies can be directly installed. Follow the instructions on the wiki [Installation](https://github.com/ydkhatri/mac_apt/wiki/Installation) page

**Comment by joachimmetz** [comment]
> Closing this. There is no requirements file as not all dependencies can be directly installed.

Note that this is makes this project unusable as a "reusable" module for me

**Comment by ydkhatri** [comment]
True, but your projects are not available as python wheel builds, which makes it difficult to install for most mac_apt users who aren't full time developers and don't want to install visual studio on windows (and wouldn't know what options to choose in VS installer either). And I don't want to spend time troubleshooting installations of pyewf, pyvmdk or pytsk3. Hence I have avoided installing mac_apt via this route. Perhaps I will revisit this again later.. I will keep it open. 

Do you plan on providing wheel builds any time soon?

**Comment by joachimmetz** [comment]
> True, but your projects are not available as python wheel builds,

They are available as msi https://github.com/log2timeline/l2tbinaries

> Do you plan on providing wheel builds any time soon?

For some projects I already do, https://pypi.org/project/libvmdk-python/#files

I'm planning to move this to python 3.8

The issue with MacOS is that python3 does not come native and historically system python was not compatible with third party python. Which leads to crazy deployment issues all the time.

Also I do not have the time to provide support for all Python versions.

> which makes it difficult to install for most mac_apt users who aren't full time developers and don't want to install visual studio on windows 

Then requirements.txt is not a good installation method for them in the first place, since it is fragile to start with.
