### ISSUE TITLE
Restoring notes – can't run mac_apt_artifact_only.py

### ISSUE THREAD

**Issue by Mmanojay** [ydkhatri/mac_apt#105]
Hi,
I lost all my notes suddenly (after I logged in to Notes app with my Gmail account). Spent quite a lot of time trying to understand where might be the problem. It had lead me here, discovering there is some sqlite database which is probably broken, and some tool for parsing its artifacts. 
This is what I know and then it is a bit a world of wonder for me as I have very poor experience in coding. I tried to run python script in Terminal `python ~/Downloads/mac_apt-master/mac_apt_artifact_only.py NOTES -o ~/Desktop/notes/NotesV7.storedata` (NotesV7.storedata from Catalina backed up on desktop) according to some [other thread](https://github.com/ydkhatri/mac_apt/issues/46), but it returned:

_File "~/Downloads/mac_apt-master/mac_apt_artifact_only.py", line 47
    plugins_info = f "The following {len(plugins)} plugins are available:"
                                                                         ^
SyntaxError: invalid syntax_

I hoped for a miracle will happen, but now I am stuck. Can you please guide me little bit how to repair the code or even if it works, what to do next? :)

**Comment by ydkhatri** [comment]
What version of python are you using? Can you post the entire console output here?

**Comment by ydkhatri** [comment]
Closing for lack of response.
