### ISSUE TITLE
Can't run mac_apt.py in macOS Ventura 

### ISSUE THREAD

**Issue by sundarleo19** [ydkhatri/mac_apt#106]
Hi,

I tried both automated and manual installation in macOS Ventura, Python 3.10. 
In automated install one or more required dependencies has failed. Please see following log. 
[mac_apt_installer_output.txt](https://github.com/ydkhatri/mac_apt/files/13422917/mac_apt_installer_output.txt)

 Is this some thing same known issue related to long file path in windows for fastchuncking. 

Issue: 

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fastchunking
  Running setup.py clean for fastchunking
Successfully built pyaff4
Failed to build fastchunking
ERROR: Could not build wheels for fastchunking, which is required to install pyproject.toml-based projects

Package    Version
---------- -------
pip        23.3.1
setuptools 68.2.2
wheel      0.41.3

**Comment by ydkhatri** [comment]
Is this a problem in Windows or macOS Ventura? 
If Windows, yes that is a known issue, follow the fix provided here: https://github.com/netleibi/fastchunking/issues/6#issuecomment-877677653

This essentially just involves creating a C:\temp folder and redirects python to use that temp folder:
```
set TMPDIR=C:\temp
pip install fastchunking
```

**Comment by ydkhatri** [comment]
Ok, it seems that you need to install pybindgen first, then install fastchunking. I've updated the wiki with a new version of the installer script that fixes this now.

**Comment by ydkhatri** [comment]
Please re-open if this is still an issue.

**Comment by sundarleo19** [comment]
Thanks it works now with the new version of the installer script.
