### ISSUE TITLE
Error – mac_apt Installation Script for macOS - Version 2.4

### ISSUE THREAD

**Issue by mm008** [ydkhatri/mac_apt#107]
Hi, 

I'm totally new to coding and tried to install mac_apt using the macOS installation script v2.4. I've installed Python 3.10 but when I run the script in Terminal I get a number of errors. Any guidance would be much appreciated!

This is what I get in Terminal when I try to run the script:

[*] mac_apt Installation Script for macOS - Version 2.4
-----------------------------------------------------------
[!] This script requires sudo privileges.
Password:
[*] macOS version is 12.7.2
[*] Would you like to specify an installation directory? [Y/n] y
[~] EX: /Users/<username>/Desktop
Directory Path: /Users/[username]/Desktop
[~] Installing mac_apt to /Users/[username]/Desktop...
[+] Installing homebrew...
curl: (22) The requested URL returned error: 404
[~] Ensuring Homebrew is up-to-date...
[+] Installing virtualenv...
[+] Downloading mac_apt from GitHub...
[!] mac_apt download failed due to 'git clone' error.
[!] Please delete the exiting 'mac_apt' folder and try again!

**Comment by ydkhatri** [comment]
Are you sure the system has access to the internet and there is nothing that is blocking the download and installation of software on there, such as an EDR tool or an application allowlisting/whitelisting software? The errors seem to indicate this.

**Comment by mm008** [comment]
Thanks for getting back to me – no I don't believe I have any such software installed, unless it came with macOS?

**Comment by ydkhatri** [comment]
Can you try again, and send over the log that gets written to /tmp/mac_apt_installer_output.txt .

**Comment by mm008** [comment]
This is what the log says:

xcrun: error: active developer path ("/Library/Developer/CommandLineTools") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.

**Comment by ydkhatri** [comment]
As the error suggests, install xcode. 
`xcode-select --install`

What version of macos are you using? What processor (Intel, arm) ?

**Comment by ydkhatri** [comment]
Closed for lack of response.
