### ISSUE TITLE
Walkthrough

### ISSUE THREAD

**Issue by Julianusss** [ydkhatri/mac_apt#110]
Hi, I have a NoteStore.sqlite file from an old laptop. However, I am not tech savvy enough to get through all the steps and get the data. I always get stuck at some point and I don't know how to do it.

Could someone walk me through while in chat with me to help me recover data? That would be very helpful to me. Thank you in advance.

**Comment by ydkhatri** [comment]
1. Copy the NoteStore.sqlite and any linked NoteStore.journal or NoteStore.wal files to a windows system. By linked, I mean the files that are present in the same folder as the main database. 
2. Download the latest mac_apt windows release and extract mac_apt_artifact_only.exe from the zip.
3. In a Command Prompt (cmd window), browse to the folder where the exe resides, then run the following command:
`mac_apt_artifact_only.exe -i C:\temp\Notestore.sqlite -o C:\temp -x NOTES`
_The above command assumes that your original files are copied to the C:\temp folder. If not replace that path with the location of wherever you copied them._
