### ISSUE TITLE
Decryption error - KEK Encoding Type 16 Handling - Fails to decrypt even with correct password

### ISSUE THREAD

**Issue by nicoleibrahim** [ydkhatri/mac_apt#116]
### Background:
Model: MacBook Air (13-inch, 2017), Intel, non-T2
OS: MacOS Mojave 10.14.6
FileVault: Enabled
Original FS: HFS
Current FS: APFS
Users: 3 (1 created under HFS, 2 created under APFS)

### Acquisition/Source Image Info:
Method: Forensic Boot of source device into Cellebrite Collector 3.6
Source Disk: disk1 APFS synthesized container
FileVault credentials entered using known password at time of acquisition
Output image type: DMG

### mac_apt version info:
MAIN-INFO-Started macOS Artifact Parsing Tool, version 1.6.5.dev (20231230)
MAIN-INFO-Python version = 3.9.6 (default, Dec  7 2023, 05:42:47)
MAIN-INFO-Pytsk  version = 20221228
MAIN-INFO-Pyewf  version = 20231119
MAIN-INFO-Pyvmdk version = 20231123
MAIN-INFO-PyAFF4 version = 0.31

### Command: 
python3 mac_apt.py -o ./test-air -p ****** -l DEBUG DMG /Volumes/ExFat/MacBookAir/test/disk1\ 2021-01-01\ 00-20-23/disk1\ Image.dmg USERS

### mac_apt error: 
Note that with a known password the KEK unwrapped successfully. However, Unwrapping the VEK fails with error "could not decrypt with credentials provided.

### Screenshot of runtime error:
![image](https://github.com/ydkhatri/mac_apt/assets/51210112/8efa7e91-645b-4b91-88e5-4b261f3543df)

### Error cause:
Screenshot of lines 472 - 495
https://github.com/ydkhatri/mac_apt/blob/master/plugins/helpers/decryptor.py

Code does not account for special handling of kek_enc_type 16, which when unwrapped in the else statement, results in an unwrapped kek 32 bytes in length which includes null padding: 
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

![image](https://github.com/ydkhatri/mac_apt/assets/51210112/7957ff0f-4f7e-4d81-a0d1-34f62b7f2d1d)

### Suggested Fix:
https://github.com/ydkhatri/mac_apt/blob/master/plugins/helpers/decryptor.py
KEK unwrapping code segment which starts on line 475. Add elif to account for kek_enc_type 16 special handling by removing \x00 byte padding
```
            # KEK unwrapping
            if kek_enc_type == 2: # for 128 bit keys, when filevauled HFS upgraded to APFS
                unwrapped_kek = unwrap(wrapped_kek[:24], user_password_key[:16])
            elif kek_enc_type == 16:
                unwrapped_kek = unwrap(wrapped_kek, user_password_key)
                unwrapped_kek = unwrapped_kek.replace(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',b'')
            else:
                unwrapped_kek = unwrap(wrapped_kek, user_password_key)
            log.debug('KEK unwrapped successfully!')
```

This worked for me.
Thanks!

**Comment by ydkhatri** [comment]
Thanks Nicole. Will update this now.

**Comment by ydkhatri** [comment]
Fixed. Was there a corresponding `vek_enc_type == 16` too ?

**Comment by nicoleibrahim** [comment]
No problem, Yogesh! Thank you! And no, no corresponding vek_enc_type == 16. Reported type of VEK was type 2.
