### ISSUE TITLE
Installation error: 'libintl.h' file not found with Python3.10

### ISSUE THREAD

**Issue by tanktacle** [ydkhatri/mac_apt#121]
Hello!

I am currently experiencing an error that seems that wants to stay with me for good. I am trying to install the libewf dependency, but I am failing miserably and I don't know what other steps to take.
I have visited a few issues here with the same problem as me, but none worked. This is the error:

```
libclocale/libclocale_support.c:26:10: fatal error: 'libintl.h' file not found
#include <libintl.h>
         ^~~~~~~~~~~
1 error generated.
error: command '/usr/bin/clang' failed with exit code 1
```

What I have tried:
1. I swapped the keyboards to US english as it was suggested in another issue, re-ran the setup.py build/install with python3.10, nothing
2. I downloaded and tried running the automated installers, v21, v21a, v23 and v24, but nothing, same error
3. I removed everything and re-did the whole process again just in case, but nothing.

I am really at my wits end, could I get some help please? : (

Thank you!

**Comment by ydkhatri** [comment]
I can't recreate this, however google searches seem to indicate that this might fix it:
```
brew unlink gettext && brew link --force gettext
```

**Comment by ydkhatri** [comment]
Closing for lack of feedback
