### ISSUE TITLE
Query Execution Failed

### ISSUE THREAD

**Issue by LowFreeKey** [ydkhatri/mac_apt#125]
Trying to recover some notes using the NOTES plugin. I have NOTESV7.storedata ,NOTESV7.storedata-shm & NOTESV7.storedata-wal . 

Running this command ` sudo python mac_apt_artifact_only.py NOTES -o /Users/lcorti/Desktop/OneMoreTest -i /Users/lcorti/Desktop/OldNotes/NotesV7.storedata-wal
`

I've tried running the entire file or the shm / wal extensions respectively and this is the error it returns. 

`AIN.NOTES-ERROR-Query  execution failed. Query was: SELECT n.Z_PK as note_id, n.ZDATECREATED as created, n.ZDATEEDITED as edited, n.ZTITLE as title,  (SELECT ZNAME from ZFOLDER where n.ZFOLDER=ZFOLDER.Z_PK) as folder,  (SELECT zf2.ZACCOUNT from ZFOLDER as zf1  LEFT JOIN ZFOLDER as zf2 on (zf1.ZPARENT=zf2.Z_PK) where n.ZFOLDER=zf1.Z_PK) as folder_parent_id,  ac.ZEMAILADDRESS as email, ac.ZACCOUNTDESCRIPTION as acc_desc, ac.ZUSERNAME as username, b.ZHTMLSTRING as data,  att.ZCONTENTID as att_id, att.ZFILEURL as file_url  FROM ZNOTE as n  LEFT JOIN ZNOTEBODY as b ON b.ZNOTE = n.Z_PK  LEFT JOIN ZATTACHMENT as att ON att.ZNOTE = n.Z_PK  LEFT JOIN ZACCOUNT as ac ON ac.Z_PK = folder_parent_id
Traceback (most recent call last):
  File "/Users/lcorti/Desktop/env/mac_apt/plugins/notes.py", line 134, in ReadNotesV2_V4_V6
    cursor = db.execute(query)
sqlite3.DatabaseError: file is not a database
MAIN.NOTES-INFO-No notes found in /Users/lcorti/Desktop/OldNotes/NotesV7.storedata-wal`

Any ideas?

**Comment by ydkhatri** [comment]
Remove the -wal in your command. You only need the run it on the main
database. It will automatically pull in data from the wal file. So run this
command:

sudo python mac_apt_artifact_only.py  -o /Users/lcorti/Desktop/OneMoreTest
-i /Users/lcorti/Desktop/OldNotes/NotesV7.storedata -l DEBUG NOTES

**Comment by LowFreeKey** [comment]
Thanks for taking a look,

If I run the plugins at the end of the command it states that I'm missing the plugin argument. Is DEBUG a plugin as well? 
Running just this `sudo python mac_apt_artifact_only.py NOTES -o /Users/lcorti/Desktop/OneMoreTest -i /Users/lcorti/Desktop/OldNotes/NotesV7.storedata`

I get `Output path was : /Users/lcorti/Desktop/OneMoreTest
MAIN-INFO-Started macOS Artifact Parsing Tool - Artifact Only mode, version 1.9.2.dev (20241011)
MAIN-INFO-Dates and times are in UTC unless the specific artifact being parsed saves it as local time!
MAIN-INFO---------------------------------------------------
MAIN-INFO-Running plugin NOTES
MAIN-INFO---------------------------------------------------
MAIN.NOTES-INFO-Module Started as standalone
MAIN.NOTES-INFO-Processing file /Users/lcorti/Desktop/OldNotes/NotesV7.storedata
MAIN.NOTES-INFO-No notes found in /Users/lcorti/Desktop/OldNotes/NotesV7.storedata
MAIN-INFO---------------------------------------------------
MAIN-INFO-Finished in time = 00:00:00
`

I know these notes aren't empty. Could it be that I am running mac_apt on another Mac than where the notes originate from?

**Comment by LowFreeKey** [comment]
I did a bit more digging with R-Studio and recovered a `com.apple.Notes.HTMLConverter` file. It seems to contain a decryption key but Ive been unsuccessful in decrypting any of the .storedata files , does mac_apt usually fetch this key when running NOTES or is it irrelevant?

**Comment by ydkhatri** [comment]
> I did a bit more digging with R-Studio and recovered a `com.apple.Notes.HTMLConverter` file. It seems to contain a decryption key but Ive been unsuccessful in decrypting any of the .storedata files , does mac_apt usually fetch this key when running NOTES or is it irrelevant?

I'm fairly certain there is no encryption by default. If you'd like, you can email me the database files (db and -wal) and I can take a look.

**Comment by LowFreeKey** [comment]
Thats very kind thank you. Have sent a Proton Drive invite.

**Comment by LowFreeKey** [comment]
Have resent the Notes directly to @swiftforsenics

**Comment by ydkhatri** [comment]
Running the program this way I've got no problems:
```
(venv312) mac_apt % python mac_apt_artifact_only.py -i /Users/superman/Downloads/Lazlo/NotesV7.storedata -o /Users/superman/Downloads/Lazlo/out -l DEBUG NOTES
Output path was : /Users/superman/Downloads/Lazlo/out
MAIN-INFO-Started macOS Artifact Parsing Tool - Artifact Only mode, version 1.9.3.dev (20241103)
MAIN-INFO-Dates and times are in UTC unless the specific artifact being parsed saves it as local time!
MAIN-DEBUG-mac_apt_artifact_only.py -i /Users/superman/Downloads/Lazlo/NotesV7.storedata -o /Users/superman/Downloads/Lazlo/out -l DEBUG NOTES
MAIN-DEBUG-Trying to create db @ /Users/superman/Downloads/Lazlo/out/mac_apt.db
MAIN-INFO---------------------------------------------------
MAIN-INFO-Running plugin NOTES
MAIN-INFO---------------------------------------------------
MAIN.NOTES-INFO-Module Started as standalone
MAIN.NOTES-DEBUG-Input file passed was: /Users/superman/Downloads/Lazlo/NotesV7.storedata
MAIN.NOTES-INFO-Processing file /Users/superman/Downloads/Lazlo/NotesV7.storedata
MAIN.NOTES-DEBUG-Opened database successfully
MAIN.NOTES-INFO-No notes found in /Users/superman/Downloads/Lazlo/NotesV7.storedata
MAIN-INFO---------------------------------------------------
MAIN-INFO-Finished in time = 00:00:00
MAIN-INFO-Review the Log file and report any ERRORs or EXCEPTIONS to the developers
```
The `-i` can accept multiple inputs, hence it may get confused. If you do `-i` first, then `-o` and other options, it should be fine.

Regarding your database, it appears to be empty, maybe it was emptied, or it didn't have much to begin with. Perhaps as you've said, you are looking at the wrong database..

**Comment by LowFreeKey** [comment]
Sounds good, Il scour the rest of the database for now.
