### ISSUE TITLE
No module named 'pyewf' when running mac_apt on High Sierra

### ISSUE THREAD

**Issue by markedphillips** [ydkhatri/mac_apt#15]
So I followed the directions exactly three times and each time, I received the following error:

```
Traceback (most recent call last):
  File "mac_apt.py", line 26, in <module>
    import pyewf
ModuleNotFoundError: No module named 'pyewf'
```

Of course I followed the instructions regarding how to install - pyewf

> Download libewf-20171104.tar.gz from https://github.com/libyal/libewf/releases Unzip and compile:

```
./configure --enable-python --with-pyprefix
make
sudo make install
```

So any thoughts? Thanks in advance!

**Comment by ydkhatri** [comment]
I haven't encountered that error on High Sierra. Are you sure libewf installs correctly? Does it encounter any errors on `make`? From the error it is likely that libewf is failing to install.

Another thing you could do is run this automated installer shell script, which will download and install mac_apt and all dependencies. Give it a try. [Download mac_aptInstall-macOS-v15.sh from this folder](https://drive.google.com/drive/folders/1lIBaEJO3SfANfISWL63fi0It6HuKLkxE?usp=sharing) 

After downloading, run ` ./mac_aptInstall-macOS-v15.sh` This will not fix any libewf problems, but just automate all the manual commands you have to run.

**Comment by markedphillips** [comment]
Thanks! It was my mistake. The machine I was on aliased python to python3 so I went back and hand installed everything being explicit and that worked. Now running it! However, I love this installer script and will use  this too! Thanks again!

**Comment by markedphillips** [comment]
Do you have a similar script for linux?

**Comment by ydkhatri** [comment]
> The machine I was on aliased python to python3 so I went back and hand installed everything being explicit and that worked.

Good! Let me know if you run into any bugs.
> Do you have a similar script for linux?

Not yet. But it is on the list of things to do!

**Comment by markedphillips** [comment]
Do you have any plans to parse FSEvents? Or is there a way to currently do this?

**Comment by ydkhatri** [comment]
It's already a plugin included here. If you installed from code, you should see it. It is not present in the windows exe as it was created after the exe was compiled.

**Comment by markedphillips** [comment]
Thank you so much! You rock! What is your preferred mechanism for private communication?

**Comment by ydkhatri** [comment]
> Thank you so much! You rock! What is your preferred mechanism for private communication?

Email works!

**Comment by siftuser** [comment]
> I haven't encountered that error on High Sierra. Are you sure libewf installs correctly? Does it encounter any errors on `make`? From the error it is likely that libewf is failing to install.
> 
> Another thing you could do is run this automated installer shell script, which will download and install mac_apt and all dependencies. Give it a try. [Download mac_aptInstall-macOS-v15.sh from this folder](https://drive.google.com/drive/folders/1lIBaEJO3SfANfISWL63fi0It6HuKLkxE?usp=sharing)
> 
> After downloading, run ` ./mac_aptInstall-macOS-v15.sh` This will not fix any libewf problems, but just automate all the manual commands you have to run.

As an FYI - I had same error "No module named pyewf" using auto install script. However, installing manually using instructions on same page worked like a charm. My guess is pyewf is bound to default python v2.7 when using auto install script ... could be totally wrong observation though :(
