### ISSUE TITLE
BASHSESSION not pulling all sessions

### ISSUE THREAD

**Issue by mrgodfrey3** [ydkhatri/mac_apt#17]
Testing in macOS 10.14.4 - only .bash_history and 2 sessions parsed on image with 4 sessions.

**Comment by ydkhatri** [comment]
Is this on one of the images you've shared with me? If yes, can you tell me which one, so I can take a look.

**Comment by mrgodfrey3** [comment]
Image #3 dated 2019-05-09

Do you have that one? I can send a link if not.

Mike Godfrey

**Comment by ydkhatri** [comment]
Fixed now in py3 branch.

**Comment by mrgodfrey3** [comment]
Awesome. I’ll run it against my images and report back.

Mike Godfrey
