### ISSUE TITLE
parser PRINTJOBS: error

### ISSUE THREAD

**Issue by Banaanhangwagen** [ydkhatri/mac_apt#21]
When executing the `PRINTJOBS`-parser, it stumbles upon a value which is not an UNIX-timestamp.

![image](https://user-images.githubusercontent.com/25983612/61776840-1eb43080-adfc-11e9-850b-c517ab9c177d.png)

The script errors and exits.

This can be bypassed the dirty way in `common.py` by adding the following under ReadUnixTime
```
                elif isinstance(unix_time, bytes) and len(unix_time) == 0:
                    unix_time = 0
```
Optionally, a error-warning can be written also.

**Comment by ydkhatri** [comment]
Can you submit the file that generates this error and also a DEBUG log? In addition, please provide more details about the image you are trying to run this on like its macOS version.

**Comment by Banaanhangwagen** [comment]
Unfortunately, I cannot send you the file. See screenshot in first post for hexview of where it goes wrong ;)

The macOS version is 10.11.6

This is the DEBUG-log output of the error:
```
2019-07-24 16:59:11|MAIN|ERROR|An exception occurred while running plugin - PRINTJOBS
Traceback (most recent call last):
  File "mac_apt.py", line 454, in <module>
    plugin.Plugin_Start(mac_info)
  File "C:\Users\REDACTED\Downloads\mac_apt-master\plugins\printjobs.py", line 64, in Plugin_Start
    cups_info = parse_cups_file_from_image(mac_info, filepath)
  File "C:\Users\REDACTED\Downloads\mac_apt-master\plugins\printjobs.py", line 168, in parse_cups_file_from_image
    return get_job_properties(request, filepath)
  File "C:\Users\REDACTED\Downloads\mac_apt-master\plugins\printjobs.py", line 150, in get_job_properties
    time_at_processing = CommonFunctions.ReadUnixTime(get_job_detail(request, "time-at-processing"))
  File "C:\Users\REDACTED\Downloads\mac_apt-master\plugins\helpers\common.py", line 90, in ReadUnixTime
    return datetime.datetime(1970, 1, 1) + datetime.timedelta(seconds=unix_time)
TypeError: unsupported type for timedelta seconds component: bytes
2019-07-24 16:59:11|MAIN|INFO|--------------------------------------------------
```

**Comment by ydkhatri** [comment]
The format of the printjob file is the same as you've shown in hex above. The timestamp is stored as 4 byte big endian, all files are handled the same way. So I'm not sure how 'bytes' is returned instead of a number. The problem must be with the pkipplib library used to parse the format. _Please try to send me a redeacted version of the file by editing it in a hex editor to overwrite all sensitive ascii strings with 'XXXX'._ You can send it to me in an email instead of posting it here publicly.

**Comment by Banaanhangwagen** [comment]
Done.

**Comment by ydkhatri** [comment]
OK, so it seems that one of the date time values here (time-at-processing) is null, the library returns an empty binary string, hence the choke-up. I've fixed this now.

**Comment by ydkhatri** [comment]
Just made a new release with this change and more. Let me know if this still does not work.
