### ISSUE TITLE
export of USERS

### ISSUE THREAD

**Issue by Banaanhangwagen** [ydkhatri/mac_apt#22]
When specifying only one parser (no matter which one), there is - as expected - an export of the files which are examined.

However, there is *always* an extra export of the USERS files (plist). This is not expected because the USERS parser was not specified in the command.
(The export of the user.plist files is also logged in the `Exported_Files_Log.csv`)

**Comment by ydkhatri** [comment]
This is normal. This is part of the default processing. mac_apt will always parse all the user info to create a users list with all user information such as user home directory, darwin folder paths, uid, gid, etc.. This information is then made available to every plugin for further processing (if needed). For example, the NOTIFICATIONS plugin needs to know each user's DARWIN_USER_DIR path. 

As a rule of thumb, every file mac_apt probes to gather information is exported. If you select the USERS plugin then this information is also exported out (but it is always parsed out).
