### ISSUE TITLE
MAIN-ERROR-Failed to load image.

### ISSUE THREAD

**Issue by nbb3210** [ydkhatri/mac_apt#23]
python3
macOS Mojave 10.14.6
![image](https://user-images.githubusercontent.com/13009951/66827833-2827e180-ef82-11e9-91de-fb34a8d58d9c.png)
what dose input_path means ? where should l download it or find it locally?

**Comment by ydkhatri** [comment]
`input_path` means path to your image file. I appears you have used it correctly. I would verify that /Users/xuqiang/Acquisition.E01 actually exists and is valid.

This is an error with pyewf. I haven't encountered this before. Can you run the script with `-l DEBUG` option. This will run the script in debug mode and may offer  more info on what is going on.

**Comment by nbb3210** [comment]
l don't have /Users/xuqiang/Acquisition.E01. How can l build it or where can l download it ?

**Comment by Raylorman** [comment]
EO1 is an image file format, you can use several free tools such as
AccessData FTK Imager to create an E01 image file from a hard drive. You
can also acquire an image in .dd format, again using several free tools. If
you use a dd,  change the mac_apt image format input to dd when selecting
your image file.

**Comment by ydkhatri** [comment]
> l don't have /Users/xuqiang/Acquisition.E01.

I think you are trying to run this live, hence the confusion.

If you want to run this live on you mac (no image), then read this page on the wiki:
https://github.com/ydkhatri/mac_apt/wiki/Sample-Usage#run-mac_apt-live-no-image-to-get-artifacts-from-local-machine

Also this one for settings you need when running it live.
https://github.com/ydkhatri/mac_apt/wiki/Known-issues-and-Workarounds

**Comment by nbb3210** [comment]
Great! It works. Thx
