### ISSUE TITLE
[Help!! Urgently] Export notes data from macbook pro

### ISSUE THREAD

**Issue by FeitianSmartcardReader** [ydkhatri/mac_apt#25]
Hi Guys

My computer is macbook pro, I got issue with my drive, but luckly, I got backup below files.
![image](https://user-images.githubusercontent.com/9547938/67383123-3351c180-f5c1-11e9-8dad-4813c1362901.png)

May please let me know how can restore my data? thanks

**Comment by ydkhatri** [comment]
Install mac_apt guide [(here](https://github.com/ydkhatri/mac_apt/wiki/Installation-for-Python3.7)), then use `mac_apt_single_artifact_only.py` and point it to your `NotesV2.storedata` file.

Sample usage:
`python mac_apt_artifact_only.py -i NotesV2.storedata -o output_folder -x -s NOTES`

**Comment by FeitianSmartcardReader** [comment]
Thanks, it helps a lot, i will build on my macOS and take a try.

And BTW, I do another way yesertday, I installed a new macOS with same version, and replacement the storedata, after open notes, all notes came back. ;-)

But I would like try your way to make sure, keep update, ;-)

**Comment by ydkhatri** [comment]
OK, will close this now.
