### ISSUE TITLE
Error after source code python 3 install

### ISSUE THREAD

**Issue by edp05373** [ydkhatri/mac_apt#30]
I get this after running the install sh and starting the env and run "python mac_apt.py -h"

Traceback (most recent call last):
  File "mac_apt.py", line 23, in <module>
    import plugins.helpers.macinfo as macinfo
  File "/Users/examiner/Desktop/mac_apt/mac_apt/plugins/helpers/macinfo.py", line 26, in <module>
    from plugins.helpers.hfs_alt import HFSVolume
  File "/Users/examiner/Desktop/mac_apt/mac_apt/plugins/helpers/hfs_alt.py", line 29, in <module>
    from plugins.helpers.btree import AttributesTree, CatalogTree, ExtentsOverflowTree
  File "/Users/examiner/Desktop/mac_apt/mac_apt/plugins/helpers/btree.py", line 18, in <module>
    from plugins.helpers.structs import *
  File "/Users/examiner/Desktop/mac_apt/mac_apt/plugins/helpers/structs.py", line 185, in <module>
    "unicode" / PaddedString(lambda ctx: ctx["length"] * 2, encoding="utf-16-be") # "unicode",
NameError: name 'PaddedString' is not defined

**Comment by jfarley248** [comment]
Try upgrading to latest version of Construct

**Comment by ydkhatri** [comment]
As pointed by Jack, this is due to a recent code update to update to the newer version of Construct library.
I just updated the Wiki installation page to reflect the new version of construct. Latest (2.9.45) works just fine. 
`pip install construct --upgrade` should fix it.

**Comment by edp05373** [comment]
Thanks guys!

**Comment by Nostramo2018** [comment]
Hello!!
I have updated construct with `pip3 install construct --upgrade`, but I still have "NameError: name 'PaddedString' is not defined"

What could I do now?

**Comment by ydkhatri** [comment]
I just tested this with latest construct and did not get any problems. 
Are you in the python virtual environment ? It is likely that you have installed this in the virtual env and then you are trying to use mac_apt  outside that environment, hence it is not seeing the upgrade. Or perhaps it is the other way around. Just ensure that wherever you installed construct is the same as where you are running mac_apt.

**Comment by FoundTheWOUT** [comment]
This prompt jump out when I run the installing script too.
Do you mean run `pip install construct --upgrade` outside the virtual env or in it?
I tried both, finnaly got the  `latest version of construct is (2.10.56)`outside, but a upgrade process inside.
After I run construct upgrade inside, the error about  'PaddedString' gone. However, when I run `python mac_apt ...`, it tell me `No module named 'xxxx'`, i am sure i am in the mac_apt env.

**Comment by ydkhatri** [comment]
> This prompt jump out when I run the installing script too.
> Do you mean run `pip install construct --upgrade` outside the virtual env or in it?
> I tried both, finnaly got the `latest version of construct is (2.10.56)`outside, but a upgrade process inside.
> After I run construct upgrade inside, the error about 'PaddedString' gone. However, when I run `python mac_apt ...`, it tell me `No module named 'xxxx'`, i am sure i am in the mac_apt env.

Everything should be inside the virtual env. Instead of version 2.10, try using 2.9.45
Do this inside your virtual env:
```
pip uninstall construct
pip install construct==2.9.45
```
This is the recommended version. Follow the instructions on wiki here:
[https://github.com/ydkhatri/mac_apt/wiki/Installation-for-Python3.7#macos-osx](https://github.com/ydkhatri/mac_apt/wiki/Installation-for-Python3.7#macos-osx)
I also updated the install script there which should do this automatically.

**Comment by FoundTheWOUT** [comment]
> > This prompt jump out when I run the installing script too.
> > Do you mean run `pip install construct --upgrade` outside the virtual env or in it?
> > I tried both, finnaly got the `latest version of construct is (2.10.56)`outside, but a upgrade process inside.
> > After I run construct upgrade inside, the error about 'PaddedString' gone. However, when I run `python mac_apt ...`, it tell me `No module named 'xxxx'`, i am sure i am in the mac_apt env.
> 
> Everything should be inside the virtual env. Instead of version 2.10, try using 2.9.45
> Do this inside your virtual env:
> 
> ```
> pip uninstall construct
> pip install construct==2.9.45
> ```
> 
> This is the recommended version. Follow the instructions on wiki here:
> https://github.com/ydkhatri/mac_apt/wiki/Installation-for-Python3.7#macos-osx
> I also updated the install script there which should do this automatically.
> 
> Just ensure that you are also trying to start mac_apt inside the virtual env. This is indicated on the terminal with a ` (env)` in the far left of the terminal prompt (on every line).
> 
> **Edit: I just tested latest version 2.10.56, and it will work too.**

I thought there are some dependencies missing in v16.
Just tested the v17 script, it worked everthing correctly. Thank you.

**Comment by ydkhatri** [comment]
Yes, the v16 script did not have all the dependencies as the code now requires more due to some newer plugins that were added recently. Thanks for testing v17 install script.
