### ISSUE TITLE
mac_apt_artifact_only tries to use nonexistent python by default

### ISSUE THREAD

**Issue by arnabanerji** [ydkhatri/mac_apt#31]
In the current release, running``./mac_apt_artifact_only -h`` after initial download gives the following output:

```
2020-04-23 14:08:53.828 mac_apt_artifact_only[43079:479791] A Python runtime not could be located.  You may need to install a framework build of Python, or edit the PyRuntimeLocations array in this application's Info.plist file.
```

Examining the ``Info.plist`` shows that the app is trying to find a version of python at ``../Frameworks/Python.framework/Versions/3.7/Python``, but ``Versions/3.7`` is empty. However, ``Versions/Current`` contains a ``Python`` file that allows the program to run successfully.

Accordingly, the package should be released with the appropriate path in ``Info.plist`` in the first place (since the Python provided is part of the package) instead of forcing users to figure this out.

**Comment by ydkhatri** [comment]
You are correct, there is a problem with this. 
`py2app` was used to convert this into a standalone package. I don't have the machine where this was compiled, but I can compare with older uploads. There should be a symbolic link under the path you mention which then points to the correct path. However, it seems that _when this is uploaded to github, the symbolic link is replaced with a copy of the file_. Also, the files no longer have the execute permissions on them. I will have to find a way around this, the problem being that github does not allow release assets to be zip files.

**Comment by ydkhatri** [comment]
OK, seems github now allows zip! I will update the binaries some time in the next 24 hours.

**Comment by arnabanerji** [comment]
Hey, thanks for looking into this so quickly!

Does this mean you'll no longer be uploading the .app format? That's what felt most counter-intuitive about all of this, though I understand the reasons as you've explained them.

**Comment by ydkhatri** [comment]
No, it will still be in the `.app` format, because there is no alternative to this. `py2app` will only create an `app` package. The only difference is that it will be inside a zip file, so you have to unzip it now before using it. 
Yes, it is counter-intuitive going into the /Contents/MacOS/ folder to run the actual program, but that is as easy as it gets (compared to installing the dependencies manually)! But now that it is a zip file, I will include a Readme file there to explain what you need to do. If you look at previous releases, it has a zip file with readme, but github then did not allow them as assets.

**Comment by arnabanerji** [comment]
True, I will admit that after spending some time trying to do the manual Python 3.7 install and running into dependency/environment issues, going back to the .app package and figuring out how to get that working was far easier and what ultimately worked. Adding the Readme back sounds like all that's necessary to keep thing simple for everyone.

Thanks for creating this utility! It helped me extract important info for work after my Notes.app stopped working out of nowhere. Now if someone could just help me figure out how to fix that, I'd be golden...

**Comment by ydkhatri** [comment]
>  if someone could just help me figure out how to fix that, I'd be golden...
What exactly do you need figured out?
