### ISSUE TITLE
vmdk Mac Images

### ISSUE THREAD

**Issue by beleka** [ydkhatri/mac_apt#4]
Hello, i tested the tool with an vmdk image and it doesn't work , does anyone know any way to make it work? or to convert it to an accepted format?

**Comment by ydkhatri** [comment]
VMDK is not supported by mac_apt. It is not currently on our development map. If you are using linux, there are plenty of options for mounting a vmdk as a raw image (like qemu). Once mouted, you can point mac_apt to the raw disk image and use the DD option to process it.
