### ISSUE TITLE
consolidated.db may not always provide the correct serial number

### ISSUE THREAD

**Issue by Banaanhangwagen** [ydkhatri/mac_apt#40]
I am parsing a HFS image with mac_apt v0.5
As expected, it finds and reads `private\var\folders\zz\zyxvpxvq6csfxvn_n00000sm00006d\C\consolidated.db`
But the found serial number in that db, is not the one we found engraved on the Mac itself.

After further inspection, we found an earlier version of `consolidated.db` in the deleted files. We were able to correctly recover this file.

This db contains the correct serial, namely as found on the device itself.

How can we explain this?
Now we know this, is it still safe to believe `consolidated.db` ?

I'll attach the two files: [consolidated.zip](https://github.com/ydkhatri/mac_apt/files/4691289/consolidated.zip)

**Comment by ydkhatri** [comment]
It is possible that the OS was not installed on this machine, instead an image from another machine was copied on the hard disk, similar to what happens in corporate environments (restoring from images). That is one explanation, there might be others.

**Comment by ydkhatri** [comment]
Or a partial image or simply copying a few files to repair certain files.. as is often recommended on various online sites to repair/reset certain aspects of your operating system. I am not sure about the significance of this database at the moment.

**Comment by Banaanhangwagen** [comment]
I'll investigate later the two other sources. I'll keep you posted.

**Comment by Banaanhangwagen** [comment]
The `cache_encryptedA` and `lokCache_encryptedA` contain also the "wrong" serial. All those files have a creation datestamp of april 2018. (also the case for directories in user-folder for example)
I found some files with datestamp october 2016, which indicates that there was a previous installation.

It's not known if the user did a simple update or some other hocus-pocus.

Finally, if one looks up the two serials[ for example here](https://everymac.com/ultimate-mac-lookup/), we see that they refer to same device and specs.

**Comment by ydkhatri** [comment]
> Finally, if one looks up the two serials[ for example here](https://everymac.com/ultimate-mac-lookup/), we see that they refer to same device and specs.

Yes, I did that too. From what I can see, it looks like a case of restore from known good image, which carries over these files from the image. 

I am closing this issue (we can still comment and discuss here after too), as this is not really a bug.
