### ISSUE TITLE
Problem with execution

### ISSUE THREAD

**Issue by tinokyp** [ydkhatri/mac_apt#44]
Thank you for making available such a great parser. 

I installed the latest version of mac_apt as per your installation instructions but I am getting errors and can't get any results. I used Python 7 as well as Python 8, updated the construct to version 2.10 and the errors are the same. Please see below:

C:\Users\TinoK>python C:\mac_apt\mac_apt.py -h
Traceback (most recent call last):
  File "C:\mac_apt\mac_apt.py", line 23, in <module>
    import plugins.helpers.macinfo as macinfo
  File "C:\mac_apt\plugins\helpers\macinfo.py", line 11, in <module>
    import biplist
ModuleNotFoundError: No module named 'biplist'

Any suggestions please?

Thank you 
Tino K.

**Comment by ydkhatri** [comment]
> ModuleNotFoundError: No module named 'biplist'

That means the `biplist` dependency was not installed. If you ran all the steps mentioned in the [wiki](https://github.com/ydkhatri/mac_apt/wiki/Installation-for-Python3.7), you should have had this installed. 

With multiple versions of python installed, it is likely that you have the dependency installed for one version and you are invoking another one.Make sure you are running the correct version of python. I would run it like so:
`C:\python37\python.exe C:\mac_apt\mac_apt.py -h`

**Comment by ydkhatri** [comment]
If you are on Windows, you can just run the exe available under Releases too.

**Comment by tinokyp** [comment]
I run Windows as you suggested and it worked. Thank you again for taking the time to reply and for the great tool you created. Tino K.
