### ISSUE TITLE
Several errors occurred in a few plugins

### ISSUE THREAD

**Issue by mnrkbys** [ydkhatri/mac_apt#47]
When I execute mac_apt_mounted_sys_data.py (which was cloned on Feb. 3, 2021), QUICKLOOK plugin and SAVEDSTATE plugin.

QUICKLOOK plugin error:

> 2021-02-04 15:51:20|MAIN|INFO|Running plugin QUICKLOOK
> 2021-02-04 15:51:20|MAIN.QUICKLOOK|INFO|QuickLook Cache data found!
> 2021-02-04 15:51:20|MAIN|ERROR|An exception occurred while running plugin - QUICKLOOK
> Traceback (most recent call last):
>   File "./mac_apt_mounted_sys_data.py", line 217, in <module>
>     plugin.Plugin_Start(mac_info)
>   File "/Users/macforensics/Documents/GitHub/mac_apt/plugins/quicklook.py", line 472, in Plugin_Start
>     parseDbNew(c, quicklook_array, quicklook_db_path, thumbnail_file, mac_info, user)
>   File "/Users/macforensics/Documents/GitHub/mac_apt/plugins/quicklook.py", line 372, in parseDbNew
>     apfs_c = export.apfs_db.conn.cursor()
> AttributeError: 'MountedMacInfoSeperateSysData' object has no attribute 'apfs_db'

SAVEDSTATE plugin error:

> 2021-02-04 15:51:20|MAIN|INFO|Running plugin SAVEDSTATE
> 2021-02-04 15:51:20|MAIN.HELPERS.MACINFO|ERROR|Exception in _GetFileSizeNoPathMod() : [Errno 2] No such file or directory: '/Volumes/Macintosh HD - Data/Users/macforensics/Library/Saved Application State/com.apple.calculator.savedState'
> 2021-02-04 15:51:20|MAIN.HELPERS.MACINFO|ERROR|Exception in _GetFileSizeNoPathMod() : [Errno 2] No such file or directory: '/Volumes/Macintosh HD - Data/Users/macforensics/Library/Saved Application State/com.apple.AppStore.savedState'
> 2021-02-04 15:51:20|MAIN.HELPERS.MACINFO|ERROR|Exception in _GetFileSizeNoPathMod() : [Errno 2] No such file or directory: '/Volumes/Macintosh HD - Data/Users/macforensics/Library/Saved Application State/com.apple.iMovieApp.savedState'
> 2021-02-04 15:51:20|MAIN.HELPERS.MACINFO|ERROR|Exception in _GetFileSizeNoPathMod() : [Errno 2] No such file or directory: '/Volumes/Macintosh HD - Data/Users/macforensics/Library/Saved Application State/com.skitch.skitch.savedState'

These .savedState files above are symlink files, but their target files don't exist.
Check .savedState file:
```
(mac_apt) macforensics@ermacforensics mac_apt % ls -al /Volumes/Macintosh\ HD\ -\ Data/Users/macforensics/Library/Saved\ Application\ State
(snip)
lrwxr-xr-x   1 macforensics  staff   128  9  5  2019 com.apple.calculator.savedState -> /Users/macforensics/Library/Containers/com.apple.calculator/Data/Library/Saved Application State/com.apple.calculator.savedState
(snip)
```

Check symlink target file (It doesn't exist):
```
(mac_apt) macforensics@ermacforensics mac_apt % ls -al /Users/macforensics/Library/Containers/com.apple.calculator/Data/Library/Saved\ Application\ State/com.apple.calculator.savedState
ls: /Users/macforensics/Library/Containers/com.apple.calculator/Data/Library/Saved Application State/com.apple.calculator.savedState: No such file or directory
```

Finally, an exception occurred like below.

> Exception ignored in: <function SqliteWriter.__del__ at 0x7f9d781657b8>
> Traceback (most recent call last):
>   File "/Users/macforensics/Documents/GitHub/mac_apt/plugins/helpers/writer.py", line 402, in __del__
> ValueError: SqliteWriter destructor, Dear coder, you forgot to close db.

I have attached a log file too.
[Log.20210204-155117.txt](https://github.com/ydkhatri/mac_apt/files/5924239/Log.20210204-155117.txt)

**Comment by ydkhatri** [comment]
I will take a look and let you know what the actual problem is, however this is what I can tell immediately. 

The QUICKLOOK plugin will not work with mounted images because the quicklook database identifies files via inode numbers. If you run it over a disk image, mac_apt builds its own apfs database and can map file paths to inode numbers. This cannot be done on live/mounted volumes. I should add some exception handling and warnings in the code.

It looks like there is a problem with symlinks referencing files that don't exist, and I need to add some more exception handling for that too.

**Comment by ydkhatri** [comment]
Fixed the exceptions from QUICKLOOK. This should now run and export the files, but won't be able to tell you its original name/path (when run in MOUNTED mode).
