### ISSUE TITLE
MAIN-ERROR-Failed to load image. Error Details are: pyewf_glob: unable to free globbed filenames. libewf_glob_free: invalid filenames.

### ISSUE THREAD

**Issue by prishah** [ydkhatri/mac_apt#51]
I am trying to recover my corrupted notes on Mac OS Catalina.

Using the following command -

python3 mac_apt.py -x -o ~/Case_Output E01 ~/Acquisition.E01 NOTES

Please know that I do not understand how to specify the input file. I am simply using the sample. I am not sure what Acquistion.E01 means. Can I run this plugin standalone? I do have the NoteStore.sqlite file handy.

**Getting following output -**

Output path was : /Users/priyank/Case_Output
MAIN-INFO-Started macOS Artifact Parsing Tool, version 1.3.1
MAIN-INFO-Dates and times are in UTC unless the specific artifact being parsed saves it as local time!
MAIN-INFO-Python version = 3.9.5 (v3.9.5:0a7dcbdb13, May  3 2021, 13:17:02) 
[Clang 6.0 (clang-600.0.57)]
MAIN-INFO-Pytsk  version = 20210419
MAIN-INFO-Pyewf  version = 20201230
MAIN-INFO-Pyvmdk version = 20210418
MAIN-INFO-PyAFF4 version = 0.33
MAIN-ERROR-Failed to load image. Error Details are: pyewf_glob: unable to free globbed filenames. libewf_glob_free: invalid filenames.

Exception ignored in: <function SqliteWriter.__del__ at 0x10b8a80d0>
Traceback (most recent call last):
  File "/Users/priyank/Downloads/mac_apt-1.3.1/plugins/helpers/writer.py", line 402, in __del__
ValueError: SqliteWriter destructor, Dear coder, you forgot to close db.
Exception ignored in: <function ExcelWriter.__del__ at 0x10b8a8c10>
Traceback (most recent call last):
  File "/Users/priyank/Downloads/mac_apt-1.3.1/plugins/helpers/writer.py", line 643, in __del__
ValueError: ExcelWriter destructor, Dear coder, you forgot to close file.

**Comment by ydkhatri** [comment]
`Acquisition.E01` refers to a full disk image in expert witness format (.E01). If you only wish to run this on the notes database, you need to use  `mac_apt_artifact_only.py` .   
See https://github.com/ydkhatri/mac_apt/wiki/Artifact-Only-Mode for usage info (with an example involving notes).

**Comment by prishah** [comment]
Thank you works like charm! Appreciate the quick response as well.
