### ISSUE TITLE
com.apple.Safari.plist under Containers folder is not analyzed

### ISSUE THREAD

**Issue by mnrkbys** [ydkhatri/mac_apt#52]
The latest mac_apt (1.3.1) does not analyze com.apple.Safari.plist under Containers folder (```/Users/*/Library/Containers/com.apple.Safari/Data/Library/Preferences/com.apple.Safari.plist```).

In addition, it is missing both AppExtensions (```/Users/*/Library/Containers/com.apple.Safari/Data/Library/Safari/AppExtensions/Extensions.plist```) and WebExtensions (```/Users/*/Library/Containers/com.apple.Safari/Data/Library/Safari/WebExtensions/Extensions.plist```).

**Comment by ydkhatri** [comment]
I will have to add them. Thanks for reporting it.

**Comment by ydkhatri** [comment]
Added in v1.4.0.
