### ISSUE TITLE
Installation pyaff4 - update wiki guide

### ISSUE THREAD

**Issue by Banaanhangwagen** [ydkhatri/mac_apt#54]
Working on Windows 10 with Python 3.9 (64bit)

When following [your guide](https://github.com/ydkhatri/mac_apt/wiki/Installation-for-Python3) for installing `pyaff4`, one requirement, namely `fastchunking`, fails to install with pip, causing pyaff4 not to be installed.

The solution for me was:
- downloading it here: https://pypi.org/project/fastchunking/#files
- unzipping
- `python setup.py build` and `python setup.py install`
- finally `pip install pyaff4-0.31-yk.zip`

**Comment by stark4n6** [comment]
This worked for me as well on Windows 10/ Python 3.9 64bit, I had issues with installing prior

**Comment by ydkhatri** [comment]
Thanks for providing a fix. I will update the guide accordingly.

**Comment by ydkhatri** [comment]
I have raised an issue here, hopefully they can fix this, so we don't have to manually install.
https://github.com/netleibi/fastchunking/issues/6

**Comment by ydkhatri** [comment]
Added to wiki guide
