### ISSUE TITLE
ReadLastGKRejectPlist() function in QUARANTINE plugin does not store its results to DB

### ISSUE THREAD

**Issue by mnrkbys** [ydkhatri/mac_apt#58]
The results of ReadLastGKRejectPlist() function are displayed with log.info(), but not stored in mac_apt.db.
Is this behavior a bug or not?

**Comment by ydkhatri** [comment]
It's not a bug, as it was not planned to be in the db. Also, I think macOS stopped using that file a while back, I didn't see it being populated in any of the newer versions. 

We could put it in the db if you think otherwise.

**Comment by mnrkbys** [comment]
Thanks for the reply.
I now understand why the analysis results are not saved in the database.
I will close this issue.
