### ISSUE TITLE
parse specific data copied on the disk

### ISSUE THREAD

**Issue by siftuser** [ydkhatri/mac_apt#66]
Is it possible to parse specific artifacts ? for ex: browser/chrome data, I collected using kape from a windows system.

I noticed that data collected using AXIOM can be parsed. What `input_type` should be supplied ? Thanks

```
python3 mac_apt.py -o /output_dir -c  input_type /input_dir  CHROME
```

**Comment by ydkhatri** [comment]
You have to use the `mac_apt_artifact_only.py` launcher script for that. Run `-h` switch to see which modules allow this. The CHROME module does work in artifact_only mode. 

You can run `mac_apt_artifact_only.py  --plugin_help CHROME` to see options for the CHROME plugin.

**Comment by siftuser** [comment]
Thanks
