### ISSUE TITLE
missing lz4.block

### ISSUE THREAD

**Issue by siftuser** [ydkhatri/mac_apt#7]
I installed it on ubuntu 18.04 having latest sans sift V3. Followed installation guide https://github.com/ydkhatri/mac_apt/wiki/Installation

I see this error .. any clue ? Thanks

python mac_apt.py -h
!!Error in plugin 'spotlight.py' at line 32 - No module named lz4.block

**Comment by ydkhatri** [comment]
`pip install lz4` should fix it.

I had forgotten to update the installation instructions following the addition of the spotlight plugin. They have now been updated to include 'lz4'. Thanks for pointing it out.
