### ISSUE TITLE
mac_info.IsValidFolderPath() always returns False?

### ISSUE THREAD

**Issue by mnrkbys** [ydkhatri/mac_apt#70]
Has the behavior of mac_info.IsValidFolderPath() changed?
IsValidFolderPath() always returns False whether I give it the correct path that exists in the disk image or the wrong path.
As a result, the CFURLCACHE and CHROME plugins will not work properly.

I have modified CFURLCACHE plugin to test it like below:
<img width="530" alt="test code" src="https://user-images.githubusercontent.com/26597618/131762399-ea5cfaca-834a-4e23-94a0-2e25369d758b.png">

The result:
```
MAIN.CFURLCACHE-INFO-/Users/macforensics/Library/Caches/ is NOT valid.
MAIN.CFURLCACHE-INFO-/Users/macforensics/Library/Caches/ZZZZ is NOT valid.
MAIN.CFURLCACHE-INFO-/Users/Guest/Library/Caches/ is NOT valid.
MAIN.CFURLCACHE-INFO-/Users/Guest/Library/Caches/ZZZZ is NOT valid.
```

I confirmed that cache folders are existed.
<img width="631" alt="APFS_Volumes" src="https://user-images.githubusercontent.com/26597618/131762533-31dfdd8f-5aac-4594-b595-a498ec72d543.png">

**Comment by ydkhatri** [comment]
That is certainly weird, I would think a lot of things would break if that didn't work. Can you try without the trailing /
So test for existence `/Users/macforensics/Library/Caches` instead of `/Users/macforensics/Library/Caches/`

If that works, that is a silly bug which I can fix.

**Comment by mnrkbys** [comment]
I've checked with the code below:
<img width="499" alt="changed test code" src="https://user-images.githubusercontent.com/26597618/131772567-8eada9ba-5270-46ef-bbad-0b2d7c627540.png">

The result is correct!!
```
MAIN.CFURLCACHE-INFO-/Users/macforensics/Library/Caches/ is valid.
MAIN.CFURLCACHE-INFO-/Users/Guest/Library/Caches/ is valid.
```

**Comment by ydkhatri** [comment]
Fixed now.
