### ISSUE TITLE
macOS Installation Script issue with virtualenv

### ISSUE THREAD

**Issue by my4n6** [ydkhatri/mac_apt#73]
Hello Yogesh, 
while using the macOS Installation Script "mac_aptInstall-macOS-v21.sh" I am getting an error: "The folder in Line 118 does not exist" and mac_apt won't install properly. It seems to be an issue dealing with virtualenv. Changing line 112 from "virtualenv --python python3 env &> /dev/null" to "python3 -m venv env &> /dev/null" did solve this problem. I am using the latest macOS 11.6, with Python 3.7.0 and latest hombrew updates. Maybe I am not the only one ;-)

Kind Regards
Stefan
my4n6

**Comment by ydkhatri** [comment]
I will have to check this and confirm the behaviour. Thanks for reporting.

**Comment by ydkhatri** [comment]
I can't seem to reproduce it, nor have I heard about this from others who've used the script. The script installs `virtualenv` on line 92, so there should not be a problem. There is a newer version of the script that logs to the /tmp folder. Try that (to debug), and reopen the issue if you think the bug persists.

New install script is here:
https://drive.google.com/uc?id=1dRoN58J7d6EdTZ4YISCWQ_ZCuA5R-0c4&export=download
