### ISSUE TITLE
Illegal hardware instruction on MacOS CATALINA

### ISSUE THREAD

**Issue by kr4n6** [ydkhatri/mac_apt#76]
Hi,

I've installed mac_apt on my MacBook Pro (mid-2010) with MacOS CATALINA (10.15.4) without any problem.

Then, I execute the following command and I get this message "ZSH: Illegal hardware instruction" and python stop working :

### python mac_apt.py -o C:\output -x E01 C:\sample_images\mojave.E01 FSEVENTS

(My image is fragmented in multiple files (E01, E02...)

I also try with a dmg file but I have the same error.

Thanks for your help,

Best regards.

**Comment by ydkhatri** [comment]
Closed due to lack or response.
