### ISSUE TITLE
Safari 15 does not already use LastSession.plist

### ISSUE THREAD

**Issue by mnrkbys** [ydkhatri/mac_apt#78]
The tabs information of Safari 15 last session are not stored to `LastSession.plist`.
Instead of it, Safari 15 will store them to `/Users/<username>/Library/Containers/com.apple.Safari/Data/Library/Safari/SafariTabs.db`.

I haven't looked into it in detail yet, but the `bookmarks` table records the list of tabs.
The `parent` column in the `bookmarks` table seems to be linked to the value of the `active_tab_group_id` column in the `windows` table.
The `windows` table also has an `is_last_session` column, and if it is set to 1, it is recognized as the last session.

`bookmarks` table
![スクリーンショット 2021-12-20 14 00 49](https://user-images.githubusercontent.com/26597618/146714219-1e00a826-40d0-4af7-abe0-8e4aed40129f.png)

`windows` table
![スクリーンショット 2021-12-20 14 00 59](https://user-images.githubusercontent.com/26597618/146714261-8e00689e-42e5-4f65-b3fd-6ce84b52b015.png)

**Comment by ydkhatri** [comment]
Good research there @mnrkbys . Perhaps over this break, I might add that.

**Comment by ydkhatri** [comment]
Added this now in  https://github.com/ydkhatri/mac_apt/commit/82d29203159556a51b29686aa8d8dd4e0db3411b

**Comment by kevinlens** [comment]
This also works for Safari Technology Preview as well, the tricky part is it disguises itself as the same regular Safari folder. It is the second folder if that's what you're looking for.
