### ISSUE TITLE
binary distribution of lzfse is missing license details

### ISSUE THREAD

**Issue by joachimmetz** [ydkhatri/mac_apt#8]
If lzfse.pyd is compiled from: https://github.com/lzfse/lzfse

From: https://github.com/lzfse/lzfse/blob/master/LICENSE
```
2.  Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
```

Please add some information about the origin, build parameters (32-bit or 64-bit, compiler used) of this binary file.

**Comment by ydkhatri** [comment]
lzfse.pyd is a 32 bit dll compiled with Visual Studio 2012. It is a fork from pylzfse project (github.com/dimkr/pylzfse) with uses code from Apple's lzfse reference implementation (http://github.com/lzfse/lzfse). 

I've added all this info to the readme file accompanying lzfse.pyd. Licenses have been uploaded to a separate folder now in the root of the project. The next releases will have accompanying license info.

**Comment by ydkhatri** [comment]
OK, will do, it is python 2.7 for now.

**Comment by joachimmetz** [comment]
Just FYI, it is only required to add the license of projects you distribute in source or binary form (if the license of the project calls for it). You don't need to include the license of every dependency (that you don't distribute as part of the project).

**Comment by joachimmetz** [comment]
Updated https://github.com/ydkhatri/mac_apt/blob/master/lzfse_dll/readme.txt LGTM, feel free to close this issue.

**Comment by ydkhatri** [comment]
Thanks.
