### ISSUE TITLE
pyewf_glob: unable to free globbed filenames error

### ISSUE THREAD

**Issue by jeremywbritt** [ydkhatri/mac_apt#81]
python3 mac_apt.py -x -o /home/sansforensics/Desktop E01 ~/macwd.e01 WIFI -l DEBUG
Output path was : /home/sansforensics/Desktop
MAIN-INFO-Started macOS Artifact Parsing Tool, version 1.4.6.dev (20211024)
MAIN-INFO-Dates and times are in UTC unless the specific artifact being parsed saves it as local time!
MAIN-DEBUG-mac_apt.py -x -o /home/sansforensics/Desktop E01 /root/macwd.e01 WIFI -l DEBUG
MAIN-INFO-Python version = 3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0]
MAIN-INFO-Pytsk  version = 20170801
MAIN-INFO-Pyewf  version = 20140808
MAIN-INFO-Pyvmdk version = 20181227
MAIN-INFO-PyAFF4 version = 0.31
MAIN-ERROR-Failed to load image. Error Details are: pyewf_glob: unable to free globbed filenames. libewf_glob_free: invalid filenames.

Exception ignored in: <function SqliteWriter.__del__ at 0x7f0b6da19ee0>
Traceback (most recent call last):
  File "/home/sansforensics/mac_apt/plugins/helpers/writer.py", line 415, in __del__
ValueError: SqliteWriter destructor, Dear coder, you forgot to close db.
Exception ignored in: <function ExcelWriter.__del__ at 0x7f0b6d99bb80>
Traceback (most recent call last):
  File "/home/sansforensics/mac_apt/plugins/helpers/writer.py", line 681, in __del__
ValueError: ExcelWriter destructor, Dear coder, you forgot to close file.

**Comment by ydkhatri** [comment]
Make sure your files are all there if your evidence consists of multiple segments (E01, E02, ...) and they are not locked somehow. Check hashes of your evidence to ensure they are all valid, then try again.

**Comment by ydkhatri** [comment]
Another problem here might be the use of "-l DEBUG" at the end. The optional parameters cannot be after the required ones. 
```
usage: mac_apt.py [-h] [-o OUTPUT_PATH] [-x] [-c] [-l LOG_LEVEL] [-p PASSWORD]
                  input_type input_path plugin [plugin ...]
```

 Try correcting the command line to:
```python3 mac_apt.py  -l DEBUG -x -o /home/sansforensics/Desktop E01 ~/macwd.e01 WIFI```

**Comment by ydkhatri** [comment]
Closed for lack of response. please reopen if you have newer information.
