### ISSUE TITLE
Sparseimage issue

### ISSUE THREAD

**Issue by mcsteezy** [ydkhatri/mac_apt#83]
Hi Yogesh,

I've just tried running mac_apt with a sparseimage input type, but it spits out saying that 'input_type' sparseimage as not being recognized. Thank you in advance!

**Comment by mcsteezy** [comment]
C:\Users\Tester\Desktop>mac_apt -o "E:\Test\Mac_Apt" -x sparseimage "N:\Test001.sparseimage" ALL
Output path was : E:\Test\Mac_Apt
MAIN-INFO-Started macOS Artifact Parsing Tool, version 1.4.3.dev (20210904)
MAIN-INFO-Dates and times are in UTC unless the specific artifact being parsed saves it as local time!
MAIN-INFO-Python version = 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
MAIN-INFO-Pytsk  version = 20190506
MAIN-INFO-Pyewf  version = 20201230
MAIN-INFO-Pyvmdk version = 20200926
MAIN-INFO-PyAFF4 version = 0.31
MAIN-INFO-Exiting -> 'input_type' sparseimage not recognized

**Comment by mcsteezy** [comment]
Hi Yogesh, "sprase" worked, but I ended up running into another error declaring that "it could not find a partition having a macOS installation on it" when there is. Any ideas would be appreciated. Here is the log:

C:\Users\Tester\Desktop>mac_apt -o "E:\Test\Mac_Apt" -x sparseimage "N:\Test001.sparseimage" ALL
Output path was : E:\ForTesting
MAIN-INFO-Started macOS Artifact Parsing Tool, version 1.4.3.dev (20210904)
MAIN-INFO-Dates and times are in UTC unless the specific artifact being parsed saves it as local time!
MAIN-INFO-Python version = 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
MAIN-INFO-Pytsk  version = 20190506
MAIN-INFO-Pyewf  version = 20201230
MAIN-INFO-Pyvmdk version = 20200926
MAIN-INFO-PyAFF4 version = 0.31
MAIN-INFO-Opened image C:\Users\Tester\Desktop>mac_apt -o "E:\Test\Mac_Apt" -x sparseimage "N:\Test001.sparseimage" ALL
MAIN-INFO-Looking at FS with volume label 'disk image'  @ offset 209735680
MAIN-ERROR-Could not open / (root folder on partition)
MAIN.DISK_REPORT-INFO-Disk info
MAIN.DISK_REPORT-INFO-Disk Size   = 5120.00 GB (5497558138880 bytes)
MAIN.DISK_REPORT-INFO-Part Scheme = GPT
MAIN.DISK_REPORT-INFO-Block size  = 512 bytes
MAIN.DISK_REPORT-INFO-Num Sectors = 10737418240.0
MAIN-WARNING-:( Could not find a partition having a macOS installation on it
MAIN-INFO---------------------------------------------------
MAIN-INFO-Finished in time = 00:00:03
MAIN-INFO-Review the Log file and report any ERRORs or EXCEPTIONS to the developers

**Comment by ydkhatri** [comment]
Another user had a similar issue, and it turned out to be a bug in Sumuri's RECON imager, which results in only the DATA partition being copied into the image and not the OS partition. mac_apt relies on both to be there. Hence the error. Sumuri told that user that the bug has been fixed in the latest version of their product, so if you reimage the system now, that should work.

**Comment by ydkhatri** [comment]
Closing for lack of further comments.

**Comment by giuseppetotaro** [comment]
Dear Yogesh,

let me comment this issue, although it is closed, as I believe it is the right place for my problem.

I've also tried to run `mac_apt` against a `sparseimage` from SUMURI, getting the same results:
```
% python3 mac_apt.py -o /tmp/output SPARSE /Volumes/RECON\ Imager\ Data/test/test.sparseimage ALL
Output path was : /tmp/output
MAIN-INFO-Started macOS Artifact Parsing Tool, version 1.6.6.dev (20240128)
MAIN-INFO-Dates and times are in UTC unless the specific artifact being parsed saves it as local time!
MAIN-INFO-Python version = 3.10.13 (main, Nov  1 2023, 16:34:31) [Clang 14.0.3 (clang-1403.0.22.14.1)]
MAIN-INFO-Pytsk  version = 20221228
MAIN-INFO-Pyewf  version = 20231119
MAIN-INFO-Pyvmdk version = 20231123
MAIN-INFO-PyAFF4 version = 0.31
MAIN-INFO-Opened image /Volumes/RECON Imager Data/test/test.sparseimage
MAIN-INFO-Looking at FS with volume label 'disk image'  @ offset 209735680
MAIN-ERROR-Could not open / (root folder on partition)
MAIN.DISK_REPORT-INFO-Disk info
MAIN.DISK_REPORT-INFO-Disk Size   = 5120.00 GB (5497558138880 bytes)
MAIN.DISK_REPORT-INFO-Part Scheme = 
MAIN.DISK_REPORT-INFO-Block size  = 512 bytes
MAIN.DISK_REPORT-INFO-Num Sectors = 10737418240.0 
MAIN-WARNING-:( Could not find a partition having a macOS installation on it
MAIN-INFO---------------------------------------------------
MAIN-INFO-Finished in time = 00:00:00
MAIN-INFO-Review the Log file and report any ERRORs or EXCEPTIONS to the developers
```

Being the target an Apple Silicon Mac started in share disk mode, only a logical acquisition of data should be possible, I guess. However, the amount of information taken out of the shared disk (which in the end is a Samba share mounted on the host) is still valuable, so I hope that `mac_apt` can still run providing useful results.

Looking forward to hearing back from you.

**Comment by ydkhatri** [comment]
Hi, can you share a sample image where I can reproduce the issue on my end
for debugging this?

**Comment by giuseppetotaro** [comment]
Hi, I've just sent you all the info to download the sparse image via email.
Looking forward to your feedback.

Thanks a lot.

**Comment by ydkhatri** [comment]
I believe this is now fixed, there was an HFS parsing error. Re-open the issue if it is not.

**Comment by giuseppetotaro** [comment]
I've tested it against sparse images created with RECON and [asla.sh](https://github.com/giuseppetotaro/asla) and I confirm it works well.
Thanks a lot for your support.
